### ISSUE TITLE
/usr/bin/ctest: Command not found

### ISSUE THREAD

**Issue by ildar** [cgreen-devs/cgreen#125]
> $ mkdir build ; cd build
> $ cmake .. ; make
> [...]
> $ make test
> Running tests...
> make: /usr/bin/ctest: Command not found
> make: *** [test] Error 127

Counter intuitive.

**Comment by thoni56** [comment]
Not sure I agree with 'Counter  intuitive'. It's as counter-intuitive as getting `No C compiler found`.

If `ctest` is installed or not is a function of your platform (details, please?) and the way you (or someone else) installed `cmake`. On Linux there are a few `cmake` components to install to get all of `CMake`s functionality.

However, you strictly don't have to use `cmake` explicitly. On the top level there is a `Makefile` that handles much of the `CMake` stuff. It also runs the unit tests for `Cgreen` without using `ctest` if you do

    make unit

And since `make` creates the out-of-source directory etc. automatically, you can just do

    git clone <url>
    cd cgreen
    make ; make unit

Does that work for you? What system are you on?

**Comment by ildar** [comment]
Ahh! I see. The ctest must be the part of cmake!
But many Linux distributions split things. Like in my case I have cmake
installed but ctest not.

**Comment by ildar** [comment]
I confirm: installing "ctest" package fixed the issue.
