### ISSUE TITLE
Where is "can_mock_a_function_macro" tested?

### ISSUE THREAD

**Issue by stanman29** [cgreen-devs/cgreen#139]
Where is "can_mock_a_function_macro" tested?

Looking in your test examples I found this macro mock:
Ensure(Mocks, can_mock_a_function_macro)

It is not in the testsuite at bottom of file
 cgreen/tests/mocks_tests.c
 
It should read something like this in the testsuite? Yes/No?
add_test_with_context(suite, Mocks, can_mock_a_function_macro);
Am I correct????

Or am I wrong and it is tested somewhere else?
Am I missing something in the testsuite?

**Comment by thoni56** [comment]
To be run by a main program test-runner, which you are referring to it should be added to the suite, just like you point out. But all `cgreen` tests are also built as dynamically loadable test libraries that are run with the `cgreen-runner`.

Both are run when you `make unit` or `make test`.

Obviously that particular test will not be included in the main program runner tests, but it is still run using `cgreen-runner` since it will discover all tests in such a library. You can see that if you do

    cgreen-runner -v build/tests/libcgreen_c_tests.so | grep can_mock_a_function_macro

Thanks for the heads up, though. I'll include it in the main program runner, too.

**Comment by thoni56** [comment]
I also forgot to mention that a handy way to ensure that a test is actually run is to invert an assert in that test. I *should* fail, if it doesn't your test setup needs looking at.
