### ISSUE TITLE
improve failure message of not_equal_to_contents_of when contents are the same

### ISSUE THREAD

**Issue by matthargett** [cgreen-devs/cgreen#14]
current output in our own test suite:
Expected [fourty_five_and_up] to [not equal contents of] [another_fourty_five_and_up]
		at offset:			[-1]

offset -1 is a pretty obtuse way to say the contents were actually the same. maybe we should forego the 'at offset' part of the message since the first line says it all?

**Comment by thoni56** [comment]
I'm thinking of extending `actual_value_not_necessary_for` but I could not find a way to know that a constraint is "not equal to contents of". There is the ConstraintType but that only indicates the data type. Since the actual comparison is made by delegation to comparer functions, the only way I can see right now is comparing the delegation to a known implementation, but that's really ugly.

Ideas?

**Comment by matthargett** [comment]
can't we check for the ConstraintType of VALUE_COMPARER and actual==-1?

**Comment by thoni56** [comment]
Aah. Didn't read that far down. I'll fix that.
