### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by saeedSarpas** [cgreen-devs/cgreen#145]
Do you have plan to add Fortran support in future? Perhaps writing a bunch of interfaces would do the job.

**Comment by thoni56** [comment]
No. I suppose you are thinking C-to-Fortran interfaces so that *Cgreen* could drive/call "units" implemented in Fortran?

To be complete it would also require some mechanism to call __mocks__ from Fortran.

The mock-mechanism of *Cgreen* is dependent on a lot of macro-magic, so AFAIK there is no way to do that for Fortran.

Open to suggenstions or PR:s that shows how to do that. But closing this.
