### ISSUE TITLE
Runnning cgreen-runner with --quiet inhibits Emacs from finding error location

### ISSUE THREAD

**Issue by deallocated** [cgreen-devs/cgreen#155]
A very tiny thing, probably just an additional newline somewhere, but anyway:

in version 1.0.0

When running cgreen-runner with --quiet the output is such that when clicking on the error in Emacs, Emacs does not send you to the location of the error:
```
#~/code/c$ cgreen-runner connect_four.so --quiet
Running "connect_four" (26 tests):connect_four.test.c:586: Failure: cf_engine -> can_create_game_state 
	Expected [s->to_move] to [not equal] [P0]
		actual value:			[0]
```
 
as opposed to 
```
~/code/c$ cgreen-runner connect_four.so
Running "connect_four" (26 tests)...
connect_four.test.c:586: Failure: cf_engine -> can_create_game_state 
	Expected [s->to_move] to [not equal] [P0]
		actual value:			[0]

Completed "cf_engine": 69 passes, 1 failure, 0 exceptions in 105ms.
Completed "connect_four": 69 passes, 1 failure, 0 exceptions in 105ms.
```
In the latter case the filename and line number are on a separate line, allowing Emacs (and I assume similarly other editors) to jump to the file and line number. In the former case (so using --quiet) Emacs gets 'confused' because of the 'Running "connect_four" ...' part and cannot jump to the error location.

Really love working with Cgreen btw. Great work guys!!

**Comment by thoni56** [comment]
Thanks for your report, and your praise!

The quiet mode output has been changed a bit since 1.0.0 but the problem you pointed to was still present, so thanks for reporting it!

The current incarnation on master looks like this:

    ................................................................
    xml_output_tests.c:4: Failure: default -> failing_test_is_listed_by_xml_reporter
        Expected [0] to [be true]
    ....

If you are using color all dots are green, except the first one on the last line denoting the failing test just before it. Perhaps we should think about collecting all failure output and presenting only the dots first...

Fixed in https://github.com/cgreen-devs/cgreen/commit/633905df71ac21c464d26e29e4f4dcf7fb78e532.

**Comment by deallocated** [comment]
Thanks for handling this so quickly!
