### ISSUE TITLE
will_return support for structs

### ISSUE THREAD

**Issue by KabooHahahein** [cgreen-devs/cgreen#163]
Some code bases return structs. It would be nice to be able to return structs in mocks. This is a debated code practice, but nonetheless, it should be supported for those developers that want to return by value.

Something similar to the unbox_double would work. Maybe unbox_struct?

**Comment by thoni56** [comment]
Agreeing about the need, but `unpack_struct()` would need size information. `double` is a known size, an arbitrary struct is not.

Maybe you can experiment with forcing the return value from `mock()` to a pointer to struct of your choosing and then doing the copy:

    struct S func(void) {
        struct S s;
        struct S *sp;
        sp = (struct S *)mock();
        memcpy(s, sp, sizeof(struct S));
        return s;
    }

**Comment by KabooHahahein** [comment]
(struct S *)mock() won't work. That's telling the compiler that the pointer is on the stack and the contents of the value on stack is the pointer address. I think this is part of the solution: 

testing_S app_test(void)
{
    uint8_t bytePtr = (uint8_t)mock();
    testing_S S;
    memcpy(&S, &bytePtr, sizeof(testing_S));
    return S;
}
(note that I'm using a typedef struct)
which could effectively could be abstracted out to unbox_struct().

However, the issue arises with will_return() because the type is casted. I don't have too much time to create a will_return_struct(S, structInstance) constraint, but basically, we need to be able to malloc the struct in the constraint and unallocate it when necessary.  That would allow us to mock struct returns and return values at will.

**Comment by thoni56** [comment]
Sorry, I forgot to mention that `will_return` in your tests then have to have corresponding allocation of the struct and send a pointer to it. That amounts to what you said. My point is that you can try exactly that strategy "manually".

And as you mention, as did I ;-) that is the gist of the code for an `unbox_struct()`.

Again, I think the need is there, I'm hesitating because I think `box`/`unbox` is very unnatural wordings in the context of tests, it is very technical, so I would not want to extend the use of that if possible to avoid. And also I'm hoping for a more "automatic" mechanism. For C++ I think it would be possible to understand how to "pack" the data in the constraint based on the datatype using overloading, in C that is harder, but might be possible using extending the API, as has been done with `double`.

Having said that, in the meantime, a PR for this would be welcome.

**Comment by thoni56** [comment]
I'm taking the opportunity here to show a working example on how to mock functions that returns structs:

    #include <cgreen/cgreen.h>
    #include <cgreen/mocks.h>
    
    typedef struct {
        int field;
    } S;
    
    /* The mock function */
    S func(void) {
        S s;
        S *sp;
    
        sp = (S *)mock();
    
        /* Copy content of struct pointed to by returned pointer */
        memcpy(&s, sp, sizeof(S));
    
        /* Return it */
        return s;
    }
    
    Ensure(can_return_struct) {
        /* Allocate a struct */
        S *sp = malloc(sizeof(S));
    
        /* Prime one field */
        sp->field = 42;
    
        /* Expect a call and return a pointer to the struct */
        expect(func, will_return(sp));
    
        /* Call our mock function which returns a struct */
        S ret = func();

        /* And assert that the field in the returned struct is propagated */
        assert_that(ret.field, is_equal_to(12));
    
        free(sp);
    }
