### ISSUE TITLE
assert_true error message

### ISSUE THREAD

**Issue by saeedSarpas** [cgreen-devs/cgreen#166]
```assert_true``` works perfectly fine however its error message is not really useful. Is there anyway you/I can improve the error message? perhaps by substituting the values of the variables and stringifying the whole statement. Would it be even possible to do this?

**Comment by thoni56** [comment]
[The documentation](https://cgreen-devs.github.io/chap1.html#_legacy_style_assertions) denotes `assert_true` as a "legacy style assert".

The modern counterpart is `assert_that` which, if you just use boolean expression instead of constraints, like

    assert_that(1 == 1);

will give much better messages.

NB. `assert_that(<boolean expression>)` is only a shorthand for `assert_that(<boolean expression>, is_true)`, which you can use for clarity. See [manual](https://cgreen-devs.github.io/chap1.html#_the_standard_constraints)

**Comment by saeedSarpas** [comment]
Ok, just using less_than, greater_than, equal_to_string, etc. is decent enough. No need to change the error message of assert_true. Please close this issue. Thanks 👍
