### ISSUE TITLE
 error: ‘assertion_tests’ does not name a type

### ISSUE THREAD

**Issue by occam25** [cgreen-devs/cgreen#176]
Hi, 
When I try to compile cgreen in cygwin64 I get this error:

[ 34%] Building CXX object tests/CMakeFiles/cgreen_cpp_tests.dir/assertion_tests.cpp.o
/home/Administrator/cgreen/tests/assertion_tests.cpp:1:1: error: ‘assertion_tests’ does not name a type 
assertion_tests.c 
^~~~~~~~~~~~~~~ 
make[2]: *** [tests/CMakeFiles/cgreen_cpp_tests.dir/build.make:63: tests/CMakeFiles/cgreen_cpp_tests.dir/assertion_tests.cpp.o] Error 1 
make[1]: *** [CMakeFiles/Makefile2:1615: tests/CMakeFiles/cgreen_cpp_tests.dir/all] Error 2 make: *** [Makefile:161: all] Error 2

I have searched on google with no result. 
I am using cygwin64 with cmake 3.6.2 and gcc 7.3.0

**Comment by occam25** [comment]
I also tried
make cygwin64

same result

**Comment by thoni56** [comment]
This could be caused by the symbolic links that should be between the `.cpp` and `.c` files.

Did you checkout using cygwin git? What does `file tests/assertion_tests.cpp` say?

Cygwin can either use Windows sym links or Cygwin native ones. Checking out symlinks from a Git repo is unfortunately not completely transparent. If you do `less tests/assertion_tests.cpp` do you get a C++ file content or just a single line of text?

If the latter, could you try to recreate the symbolic links between the `.cpp` and `.c` files in the `tests` directory and try again?

**Comment by occam25** [comment]
It turned out that cpp files should be links to their corresponding c files but they were just text files with the c file name inside (windows magic, I guess)
After deleting cpp files and creating real links it compiled ok

**Comment by thoni56** [comment]
[Here's a description](https://www.joshkel.com/2018/01/18/symlinks-in-windows/) of the problem and how to configure Windows, Git and Cygwin to play nice to each other.

No test fails in my cygwin setup.

You can also try `make unit` to get more 'cgreen-ish' error reporting, instead of running through CMakes test harness.

**Comment by occam25** [comment]
thanks @thoni56 , just for you to know, the tests that failed were because the end lines in files were also in Windows style (\r\n) and, because of that, all the tests that compare its output with an expected result failed.
After converting them to unix style (\n) with dos2unix command the problem was solved. 
No all work fine  : )
Thanks!

**Comment by thoni56** [comment]
Thanks for that information. I'm not sure I know the reason for the different line endings. I seem to have correct/working ones. Git has some magic for this, so maybe it depends on your Git settings too.

But I'll keep that in mind if there are more examples.

BTW, `make cygwin64` is only left over from earlier attempts at building on both cygwin32 and cygwin64 in which I tried to build both and keep them in parallel. But that did not work out so well, since Cygwin is not supporting any multi-arch-like approach.
