### ISSUE TITLE
cgreen-debug which installed to /usr/bin is not a executive or script.

### ISSUE THREAD

**Issue by alvinchchen** [cgreen-devs/cgreen#212]
Hello Thoni,

During the debian packaging, Lintian complains `cgreen-debug` which installed to `/usr/bin` is not a executive or script.
I found a comment in `cgreen-debug`  

```
# This is actually not that script, but a template for argbash
```
Since it cant be executed directly, I think `/usr/share/misc` may be a more suitable place to install it.

**Comment by thoni56** [comment]
No, it is an executable script which should be installed into `/usr/bin`. I don't know why Lintian complains.

That script, `cgreen-debug` is generated from a template in which the comment "This is not actually that script..." resides. But that is copied into the generated script so that can make you a bit confused about what is what ;-) And IIRC you can use the script itself as that template, which is even more confusing...

I've clarified this a bit in the script, or template ;-).
