### ISSUE TITLE
Remove use of CGREEN_PER_TEST_TIMEOUT environment variable usage?

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#28]
There is code in the runner which investigates the use of an environment variable, CGREEN_PER_TEST_TIMEOUT, to set a `die_in()` around every test run.

This is not documented anywhere, and it is easy to use `die_in()` in your tests. Is there a scenario where this is not sufficient? Is anyone we know of using this?

I'm considering removing this duplicated functionality. Or we should document it. But primarily I'd like to discuss scenarios.

**Comment by matthargett** [comment]
(more spelunking with git blame and git log...)
Judging by the commit this came in on (2dfafd6f), this was brought in from a fork that a flash-storage client had in their win32 build. If memory serves, they needed to adjust the default "hung test" timeout for algorithmic-complex unit tests that ran too slow on some of their lower-end developer laptops. We may have used it at a networking appliance client as well where an over-subscribed VM-based CI system meant the need for more flexibility in test timeout while we racked new hardware and tuned the Jenkins instances.

So, those are the scenarios. The environment variable was so that it could be set in the Jenkins config before the makefile was called.

**Comment by thoni56** [comment]
Thanks. I've added test for it in #31 so it's somewhat official now. Closing this.
