### ISSUE TITLE
pull BDD style syntax to top of documentation

### ISSUE THREAD

**Issue by matthargett** [cgreen-devs/cgreen#3]
Some users are using the old syntax because the BDD syntax is the fourth or fifth document down. Let's make it a first class citizen, finally :)

**Comment by thoni56** [comment]
I'll have look how to improve that.

**Comment by thoni56** [comment]
First 3 chapters done. Will continue working through the documentation. Fairly straight forward. Most serious issue found is that we need to figure out a way to match what was previously "reusing fixtures" feature. (As in chapter "Building composite test suites".)

Maybe also where we should put the generated documentation... You can almost read it in the source tree, doc/cgreen-guide-en.asciidoc but since the asciidoc generator GitHub uses doesn't do "include::" the source and output are not visible...

**Comment by thoni56** [comment]
I've created a GitHub Pages repo, `cgreen-devs.github.io` for building the Cgreen web. For now it's just the [generated documentation](https://cgreen-devs.github.io).

**Comment by thoni56** [comment]
I'm closing this one now since I think the current documentation addresses the initial concern. I'll continue with the docs under some other #.
