### ISSUE TITLE
Default text reporter does not show names of failed tests

### ISSUE THREAD

**Issue by larsks** [cgreen-devs/cgreen#321]
Running a suite of 15 tests with one failing assert, I see:

```
$ cgreen-runner test_picocom.so
Running "test_picocom" (5 tests)...
  "ConfigFile": 14 passes, 1 failure in 2ms.
Completed "test_picocom": 14 passes, 1 failure in 2ms.
```

What failed? Who knows! I tried adding `--verbose` to see if that would help, but while it showed the name of discovered tests, it still doesn't report any details on failures.

This doesn't match the output shown in the [documentation](https://cgreen-devs.github.io/cgreen/cgreen-guide-en.html#runner), which looks like this:

```
$ cgreen-runner first_test.so
Running "first_tests" (2 tests)...
first_tests.c:12: Failure: Cgreen -> fails_this_test 
	Expected [0 == 1] to [be true]
```

That output clearly shows both the test name and the failed assert.

Is this a bug in the current release, or am I doing something wrong on my end? I'm using the 1.6.2 release; I'm going to build from source and see if I see the same behavior.

**Comment by larsks** [comment]
Oh, I see the problem!

One of my tests calls code that generates a lot of output on stdout, so I called:

```
fclose(stdout);
```

While this doesn't suppress the general output from cgreen; it *does* suppress the individual test results.

Is there a "correct" way to suppress output from the code under test without suppressing output from cgreen?

**Comment by thoni56** [comment]
Sorry, no, there is no officially supported way. The "normal" text-reporter prints to stdout, and it does it from the forked child process that runs the test. So closing stdout in the test will get you exactly the effect that you see.

However, there is a thing that you can try (I haven't), and maybe I shouldn't tell you this ;-)

There is an internal function, `set_text_reporter_printer()`, which is implemented to let *Cgreen*'s own tests capture the output. It might be possible to use that if you want to make a temporary hack to redirect the *Cgreen* output from a specific test, to `stderr` for example.

The specifics can be seen in the beginning of `src/text_reporter.c` and since it's not supported you will have to copy the prototypes. You also need to get the reporter, which I _think_ you can do with `get_test_reporter()`.

But all of this is totally unsupport, may change at any time, and is also untested and unverified by me.
