### ISSUE TITLE
Wrong number of tests in the 'main' suite

### ISSUE THREAD

**Issue by saeedSarpas** [cgreen-devs/cgreen#45]
I'm not sure if it's a problem from my side or it's related to cgreen (or in general if it's a problem at all!) but after compiling and running the tests, I'm getting this output:

    Completed "reordering_fourier_input_tests": 16 passes, 0 failures, 0 exceptions in 0ms.
    Completed "convert_real_delta_to_complex_tests": 32 passes, 0 failures, 0 exceptions in 1ms.
    Completed "main": 32 passes, 0 failures, 0 exceptions in 1ms.

as you can see, the number of tests accumulate suite by suite instead of reporting the number of tests in each suite! I have 16 tests in each suite and as you can see the number which is reported in front of ```convert_real_delta_to_complex_tests``` is the sum of the last suite tests and the tests of current suite itself. Here is my main function:

    #include <cgreen/cgreen.h>
    
    TestSuite *reordering_fourier_input_tests();
    TestSuite *convert_real_delta_to_complex_tests ();
    
    int main(int argc, char **argv) {
        TestSuite *suite = create_test_suite();
    
        add_suite(suite, reordering_fourier_input_tests());
        add_suite(suite, convert_real_delta_to_complex_tests());
    
        if (argc > 1) {
            return run_single_test(suite, argv[1], create_text_reporter());
        }
    
        return run_test_suite(suite, create_text_reporter());
    }

**Comment by thoni56** [comment]
Yes, currently that is the way it works, aggregating the tallying. We've had some discussion around this, and jury is still out on the question about which is the better.

There are also some situations, notably multi-level nested suites, that would give kind of a strange output.

With the current implementation you get a strictly growing test count as the tests are executed. You might look at the numbers as the current "status" rather than a tally of the number of tests in each suite/context.

In any case, this is the way it works now. Are there any particular reasons you'd like to have it otherwise?

**Comment by saeedSarpas** [comment]
No, there isn't any special reason for my question. I just found it a little counter intuitive.
By the way, thanks for your great work.

**Comment by thoni56** [comment]
Thanks. Then I'll close this issue.
